chi_crime_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: {{kv('GCP_PROJECT_ID')}}
      dataset: dbt_chi_crime_pj        # 👈 where dbt builds models
      location: us-central1
      keyfile: {{kv('GCP_CREDS')}}    # 👈 path to your service account JSON inside container
      threads: 4
