version: 2

sources:
  - name: staging   # Logical name you choose for use in dbt code
    database: chi-crime-project  # GCP Project ID that owns the data
    schema: chi_crime_dataset  # BigQuery dataset name (like `staging`, `raw`, etc.)

    tables:
      - name: chi_crime_all   # Table name inside the dataset