version: 2

seeds: 
  - name: iucr_code_lookup
    description: >
      Illinois Uniform Crime Reporting (IUCR) codes are four digit codes that law enforcement agencies 
      use to classify criminal incidents when taking individual reports. These codes are also used to 
      aggregate types of cases for statistical purposes. In Illinois, the Illinois State Police establish 
      IUCR codes, but the agencies can add codes to suit their individual needs. The Chicago Police Department 
      currently uses more than 400 IUCR codes to classify criminal offenses, divided into “Index” and 
      “Non-Index” offenses. Index offenses are the offenses that are collected nation-wide by the 
      Federal Bureaus of Investigation’s Uniform Crime Reports program to document crime trends 
      over time (data released semi-annually), and include murder, criminal sexual assault, robbery, 
      aggravated assault & battery, burglary, theft, motor vehicle theft, and arson. Non-index 
      offenses are all other types of criminal incidents, including vandalism, weapons violations, 
      public peace violations, etc.